#!/bin/bash
touch lib_text.txt
touch con_text.txt

cat personalities/bloomberg/MASTER.txt > lib_text.txt
cat personalities/limbaugh/MASTER.txt > con_text.txt
gram=3
i=1
while [ $i -le 2 ]
do
	printf "Turd Sandwich:\n "
	python src/Opinion_Bot.py con_text.txt $gram -o lib_text.txt
	printf "\n\n\n"
	sleep 3
	printf "Giant Douche:\n " 
	python src/Opinion_Bot.py lib_text.txt $gram -o con_text.txt
	printf "\n\n\n"

	(( i++ ))
done

rm lib_text.txt
rm con_text.txt
